test_that("req_steer returns correct structure", {
  result <- req_steer(bw = 150, dg = 0.8)
  expect_s3_class(result, "tbl_df")
  expect_equal(result$sex, "steer")
  expect_equal(result$BW_kg, 150)
  expect_equal(result$ADG_kg, 0.8)
  expect_true(all(c("CP_g", "ME_Mcal", "NEg_Mcal", "Ca_g", "P_g") %in% names(result)))
  expect_equal(result$CP_g, 531.7223, tolerance = 0.001)
  expect_equal(result$ME_Mcal, 9.2764, tolerance = 0.001)
  expect_equal(result$NEg_Mcal, 1.8276, tolerance = 0.001)
  expect_equal(result$Ca_g, 25.8908, tolerance = 0.001)
  expect_equal(result$P_g, 11.8142, tolerance = 0.001)
})

test_that("req_bull returns correct structure", {
  result <- req_bull(bw = 150, dg = 0.8)
  expect_s3_class(result, "tbl_df")
  expect_equal(result$sex, "bull")
  expect_equal(result$BW_kg, 150)
  expect_equal(result$ADG_kg, 0.8)
  expect_true(all(c("CP_g", "ME_Mcal", "NEg_Mcal", "Ca_g", "P_g") %in% names(result)))
  expect_equal(result$CP_g, 541.6046, tolerance = 0.001)
  expect_equal(result$ME_Mcal, 8.7561, tolerance = 0.001)
  expect_equal(result$NEg_Mcal, 1.4710, tolerance = 0.001)
  expect_equal(result$Ca_g, 26.6065, tolerance = 0.001)
  expect_equal(result$P_g, 12.0454, tolerance = 0.001)
})
